#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ntl
Version  : 11.3.2
Release  : 3
URL      : https://www.shoup.net/ntl/ntl-11.3.2.tar.gz
Source0  : https://www.shoup.net/ntl/ntl-11.3.2.tar.gz
Summary  : A Library for doing Number Theory
Group    : Development/Tools
License  : LGPL-2.1
Requires: ntl-lib = %{version}-%{release}
Requires: ntl-license = %{version}-%{release}
BuildRequires : gmp-dev
Patch1: build.patch

%description
NTL  -- a library for doing numbery theory --  version 11.3.2
Release date: 2018.11.15

%package dev
Summary: dev components for the ntl package.
Group: Development
Requires: ntl-lib = %{version}-%{release}
Provides: ntl-devel = %{version}-%{release}
Requires: ntl = %{version}-%{release}

%description dev
dev components for the ntl package.


%package doc
Summary: doc components for the ntl package.
Group: Documentation

%description doc
doc components for the ntl package.


%package lib
Summary: lib components for the ntl package.
Group: Libraries
Requires: ntl-license = %{version}-%{release}

%description lib
lib components for the ntl package.


%package license
Summary: license components for the ntl package.
Group: Default

%description license
license components for the ntl package.


%prep
%setup -q -n ntl-11.3.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553993759
pushd src
%configure --disable-static SHARED=on
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1553993759
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ntl
cp doc/copying.txt %{buildroot}/usr/share/package-licenses/ntl/doc_copying.txt
pushd src
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/NTL/ALL_FEATURES.h
/usr/include/NTL/BasicThreadPool.h
/usr/include/NTL/ConfigLog.h
/usr/include/NTL/FFT.h
/usr/include/NTL/FFT_impl.h
/usr/include/NTL/FacVec.h
/usr/include/NTL/GF2.h
/usr/include/NTL/GF2E.h
/usr/include/NTL/GF2EX.h
/usr/include/NTL/GF2EXFactoring.h
/usr/include/NTL/GF2X.h
/usr/include/NTL/GF2XFactoring.h
/usr/include/NTL/GF2XVec.h
/usr/include/NTL/HAVE_ALIGNED_ARRAY.h
/usr/include/NTL/HAVE_AVX.h
/usr/include/NTL/HAVE_AVX2.h
/usr/include/NTL/HAVE_AVX512F.h
/usr/include/NTL/HAVE_BUILTIN_CLZL.h
/usr/include/NTL/HAVE_CHRONO_TIME.h
/usr/include/NTL/HAVE_COPY_TRAITS1.h
/usr/include/NTL/HAVE_COPY_TRAITS2.h
/usr/include/NTL/HAVE_FMA.h
/usr/include/NTL/HAVE_LL_TYPE.h
/usr/include/NTL/HAVE_MACOS_TIME.h
/usr/include/NTL/HAVE_PCLMUL.h
/usr/include/NTL/HAVE_POSIX_TIME.h
/usr/include/NTL/HAVE_SSSE3.h
/usr/include/NTL/HNF.h
/usr/include/NTL/LLL.h
/usr/include/NTL/Lazy.h
/usr/include/NTL/LazyTable.h
/usr/include/NTL/MatPrime.h
/usr/include/NTL/PD.h
/usr/include/NTL/PackageInfo.h
/usr/include/NTL/REPORT_ALL_FEATURES.h
/usr/include/NTL/RR.h
/usr/include/NTL/SmartPtr.h
/usr/include/NTL/WordVector.h
/usr/include/NTL/ZZ.h
/usr/include/NTL/ZZVec.h
/usr/include/NTL/ZZX.h
/usr/include/NTL/ZZXFactoring.h
/usr/include/NTL/ZZ_limbs.h
/usr/include/NTL/ZZ_p.h
/usr/include/NTL/ZZ_pE.h
/usr/include/NTL/ZZ_pEX.h
/usr/include/NTL/ZZ_pEXFactoring.h
/usr/include/NTL/ZZ_pX.h
/usr/include/NTL/ZZ_pXFactoring.h
/usr/include/NTL/config.h
/usr/include/NTL/ctools.h
/usr/include/NTL/fileio.h
/usr/include/NTL/gmp_aux.h
/usr/include/NTL/lip.h
/usr/include/NTL/lzz_p.h
/usr/include/NTL/lzz_pE.h
/usr/include/NTL/lzz_pEX.h
/usr/include/NTL/lzz_pEXFactoring.h
/usr/include/NTL/lzz_pX.h
/usr/include/NTL/lzz_pXFactoring.h
/usr/include/NTL/mach_desc.h
/usr/include/NTL/mat_GF2.h
/usr/include/NTL/mat_GF2E.h
/usr/include/NTL/mat_RR.h
/usr/include/NTL/mat_ZZ.h
/usr/include/NTL/mat_ZZ_p.h
/usr/include/NTL/mat_ZZ_pE.h
/usr/include/NTL/mat_lzz_p.h
/usr/include/NTL/mat_lzz_pE.h
/usr/include/NTL/mat_poly_ZZ.h
/usr/include/NTL/mat_poly_ZZ_p.h
/usr/include/NTL/mat_poly_lzz_p.h
/usr/include/NTL/matrix.h
/usr/include/NTL/new.h
/usr/include/NTL/pair.h
/usr/include/NTL/pair_GF2EX_long.h
/usr/include/NTL/pair_GF2X_long.h
/usr/include/NTL/pair_ZZX_long.h
/usr/include/NTL/pair_ZZ_pEX_long.h
/usr/include/NTL/pair_ZZ_pX_long.h
/usr/include/NTL/pair_lzz_pEX_long.h
/usr/include/NTL/pair_lzz_pX_long.h
/usr/include/NTL/pd_FFT.h
/usr/include/NTL/quad_float.h
/usr/include/NTL/sp_arith.h
/usr/include/NTL/thread.h
/usr/include/NTL/tools.h
/usr/include/NTL/vec_GF2.h
/usr/include/NTL/vec_GF2E.h
/usr/include/NTL/vec_GF2XVec.h
/usr/include/NTL/vec_RR.h
/usr/include/NTL/vec_ZZ.h
/usr/include/NTL/vec_ZZVec.h
/usr/include/NTL/vec_ZZ_p.h
/usr/include/NTL/vec_ZZ_pE.h
/usr/include/NTL/vec_double.h
/usr/include/NTL/vec_long.h
/usr/include/NTL/vec_lzz_p.h
/usr/include/NTL/vec_lzz_pE.h
/usr/include/NTL/vec_quad_float.h
/usr/include/NTL/vec_ulong.h
/usr/include/NTL/vec_vec_GF2.h
/usr/include/NTL/vec_vec_GF2E.h
/usr/include/NTL/vec_vec_RR.h
/usr/include/NTL/vec_vec_ZZ.h
/usr/include/NTL/vec_vec_ZZ_p.h
/usr/include/NTL/vec_vec_ZZ_pE.h
/usr/include/NTL/vec_vec_long.h
/usr/include/NTL/vec_vec_lzz_p.h
/usr/include/NTL/vec_vec_lzz_pE.h
/usr/include/NTL/vec_vec_ulong.h
/usr/include/NTL/vec_xdouble.h
/usr/include/NTL/vector.h
/usr/include/NTL/version.h
/usr/include/NTL/xdouble.h
/usr/lib64/libntl.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/NTL/BasicThreadPool.cpp.html
/usr/share/doc/NTL/BasicThreadPool.txt
/usr/share/doc/NTL/GF2.cpp.html
/usr/share/doc/NTL/GF2.txt
/usr/share/doc/NTL/GF2E.cpp.html
/usr/share/doc/NTL/GF2E.txt
/usr/share/doc/NTL/GF2EX.cpp.html
/usr/share/doc/NTL/GF2EX.txt
/usr/share/doc/NTL/GF2EXFactoring.cpp.html
/usr/share/doc/NTL/GF2EXFactoring.txt
/usr/share/doc/NTL/GF2X.cpp.html
/usr/share/doc/NTL/GF2X.txt
/usr/share/doc/NTL/GF2XFactoring.cpp.html
/usr/share/doc/NTL/GF2XFactoring.txt
/usr/share/doc/NTL/GF2XVec.cpp.html
/usr/share/doc/NTL/GF2XVec.txt
/usr/share/doc/NTL/HNF.cpp.html
/usr/share/doc/NTL/HNF.txt
/usr/share/doc/NTL/LLL.cpp.html
/usr/share/doc/NTL/LLL.txt
/usr/share/doc/NTL/Lazy.cpp.html
/usr/share/doc/NTL/Lazy.txt
/usr/share/doc/NTL/LazyTable.cpp.html
/usr/share/doc/NTL/LazyTable.txt
/usr/share/doc/NTL/RR.cpp.html
/usr/share/doc/NTL/RR.txt
/usr/share/doc/NTL/SmartPtr.cpp.html
/usr/share/doc/NTL/SmartPtr.txt
/usr/share/doc/NTL/ZZ.cpp.html
/usr/share/doc/NTL/ZZ.txt
/usr/share/doc/NTL/ZZVec.cpp.html
/usr/share/doc/NTL/ZZVec.txt
/usr/share/doc/NTL/ZZX.cpp.html
/usr/share/doc/NTL/ZZX.txt
/usr/share/doc/NTL/ZZXFactoring.cpp.html
/usr/share/doc/NTL/ZZXFactoring.txt
/usr/share/doc/NTL/ZZ_limbs.cpp.html
/usr/share/doc/NTL/ZZ_limbs.txt
/usr/share/doc/NTL/ZZ_p.cpp.html
/usr/share/doc/NTL/ZZ_p.txt
/usr/share/doc/NTL/ZZ_pE.cpp.html
/usr/share/doc/NTL/ZZ_pE.txt
/usr/share/doc/NTL/ZZ_pEX.cpp.html
/usr/share/doc/NTL/ZZ_pEX.txt
/usr/share/doc/NTL/ZZ_pEXFactoring.cpp.html
/usr/share/doc/NTL/ZZ_pEXFactoring.txt
/usr/share/doc/NTL/ZZ_pX.cpp.html
/usr/share/doc/NTL/ZZ_pX.txt
/usr/share/doc/NTL/ZZ_pXFactoring.cpp.html
/usr/share/doc/NTL/ZZ_pXFactoring.txt
/usr/share/doc/NTL/arrow1.gif
/usr/share/doc/NTL/arrow2.gif
/usr/share/doc/NTL/arrow3.gif
/usr/share/doc/NTL/config.txt
/usr/share/doc/NTL/conversions.txt
/usr/share/doc/NTL/copying.txt
/usr/share/doc/NTL/flags.txt
/usr/share/doc/NTL/lzz_p.cpp.html
/usr/share/doc/NTL/lzz_p.txt
/usr/share/doc/NTL/lzz_pE.cpp.html
/usr/share/doc/NTL/lzz_pE.txt
/usr/share/doc/NTL/lzz_pEX.cpp.html
/usr/share/doc/NTL/lzz_pEX.txt
/usr/share/doc/NTL/lzz_pEXFactoring.cpp.html
/usr/share/doc/NTL/lzz_pEXFactoring.txt
/usr/share/doc/NTL/lzz_pX.cpp.html
/usr/share/doc/NTL/lzz_pX.txt
/usr/share/doc/NTL/lzz_pXFactoring.cpp.html
/usr/share/doc/NTL/lzz_pXFactoring.txt
/usr/share/doc/NTL/mat_GF2.cpp.html
/usr/share/doc/NTL/mat_GF2.txt
/usr/share/doc/NTL/mat_GF2E.cpp.html
/usr/share/doc/NTL/mat_GF2E.txt
/usr/share/doc/NTL/mat_RR.cpp.html
/usr/share/doc/NTL/mat_RR.txt
/usr/share/doc/NTL/mat_ZZ.cpp.html
/usr/share/doc/NTL/mat_ZZ.txt
/usr/share/doc/NTL/mat_ZZ_p.cpp.html
/usr/share/doc/NTL/mat_ZZ_p.txt
/usr/share/doc/NTL/mat_ZZ_pE.cpp.html
/usr/share/doc/NTL/mat_ZZ_pE.txt
/usr/share/doc/NTL/mat_lzz_p.cpp.html
/usr/share/doc/NTL/mat_lzz_p.txt
/usr/share/doc/NTL/mat_lzz_pE.cpp.html
/usr/share/doc/NTL/mat_lzz_pE.txt
/usr/share/doc/NTL/mat_poly_ZZ.cpp.html
/usr/share/doc/NTL/mat_poly_ZZ.txt
/usr/share/doc/NTL/mat_poly_ZZ_p.cpp.html
/usr/share/doc/NTL/mat_poly_ZZ_p.txt
/usr/share/doc/NTL/mat_poly_lzz_p.cpp.html
/usr/share/doc/NTL/mat_poly_lzz_p.txt
/usr/share/doc/NTL/matrix.cpp.html
/usr/share/doc/NTL/matrix.txt
/usr/share/doc/NTL/names.txt
/usr/share/doc/NTL/pair.cpp.html
/usr/share/doc/NTL/pair.txt
/usr/share/doc/NTL/quad_float.cpp.html
/usr/share/doc/NTL/quad_float.txt
/usr/share/doc/NTL/sedscript.txt
/usr/share/doc/NTL/tools.cpp.html
/usr/share/doc/NTL/tools.txt
/usr/share/doc/NTL/tour-ack.html
/usr/share/doc/NTL/tour-changes.html
/usr/share/doc/NTL/tour-ex1.html
/usr/share/doc/NTL/tour-ex2.html
/usr/share/doc/NTL/tour-ex3.html
/usr/share/doc/NTL/tour-ex4.html
/usr/share/doc/NTL/tour-ex5.html
/usr/share/doc/NTL/tour-ex6.html
/usr/share/doc/NTL/tour-ex7.html
/usr/share/doc/NTL/tour-examples.html
/usr/share/doc/NTL/tour-gf2x.html
/usr/share/doc/NTL/tour-gmp.html
/usr/share/doc/NTL/tour-impl.html
/usr/share/doc/NTL/tour-intro.html
/usr/share/doc/NTL/tour-modules.html
/usr/share/doc/NTL/tour-roadmap.html
/usr/share/doc/NTL/tour-struct.html
/usr/share/doc/NTL/tour-time.html
/usr/share/doc/NTL/tour-tips.html
/usr/share/doc/NTL/tour-unix.html
/usr/share/doc/NTL/tour-win.html
/usr/share/doc/NTL/tour.html
/usr/share/doc/NTL/vec_GF2.cpp.html
/usr/share/doc/NTL/vec_GF2.txt
/usr/share/doc/NTL/vec_GF2E.cpp.html
/usr/share/doc/NTL/vec_GF2E.txt
/usr/share/doc/NTL/vec_RR.cpp.html
/usr/share/doc/NTL/vec_RR.txt
/usr/share/doc/NTL/vec_ZZ.cpp.html
/usr/share/doc/NTL/vec_ZZ.txt
/usr/share/doc/NTL/vec_ZZ_p.cpp.html
/usr/share/doc/NTL/vec_ZZ_p.txt
/usr/share/doc/NTL/vec_ZZ_pE.cpp.html
/usr/share/doc/NTL/vec_ZZ_pE.txt
/usr/share/doc/NTL/vec_lzz_p.cpp.html
/usr/share/doc/NTL/vec_lzz_p.txt
/usr/share/doc/NTL/vec_lzz_pE.cpp.html
/usr/share/doc/NTL/vec_lzz_pE.txt
/usr/share/doc/NTL/vector.cpp.html
/usr/share/doc/NTL/vector.txt
/usr/share/doc/NTL/version.cpp.html
/usr/share/doc/NTL/version.txt
/usr/share/doc/NTL/xdouble.cpp.html
/usr/share/doc/NTL/xdouble.txt

%files lib
%defattr(-,root,root,-)
/usr/lib64/libntl.so.39
/usr/lib64/libntl.so.39.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ntl/doc_copying.txt
