#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ntl
Version  : 11.3.2
Release  : 1
URL      : https://www.shoup.net/ntl/ntl-11.3.2.tar.gz
Source0  : https://www.shoup.net/ntl/ntl-11.3.2.tar.gz
Summary  : A Library for doing Number Theory
Group    : Development/Tools
License  : LGPL-2.1
Requires: ntl-license = %{version}-%{release}
BuildRequires : gmp-dev
Patch1: build.patch

%description
NTL  -- a library for doing numbery theory --  version 11.3.2
Release date: 2018.11.15

%package license
Summary: license components for the ntl package.
Group: Default

%description license
license components for the ntl package.


%prep
%setup -q -n ntl-11.3.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553993418
pushd src
%configure --disable-static
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1553993418
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ntl
cp doc/copying.txt %{buildroot}/usr/share/package-licenses/ntl/doc_copying.txt
pushd src
%make_install
popd

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ntl/doc_copying.txt
